version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/exim"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
